"""add new webhook fields


Revision ID: f30cf048c228
Revises: ab0bae02578f
Create Date: 2022-06-15 21:05:34.851857

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f30cf048c228"
down_revision = "ab0bae02578f"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("webhook_urls", sa.Column("webhook_type", sa.String(), nullable=True))
    op.add_column("webhook_urls", sa.Column("scheduled_time", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_urls", "scheduled_time")
    op.drop_column("webhook_urls", "webhook_type")
    # ### end Alembic commands ###
