"""'Add summary to recipe instructions'

Revision ID: 3897397b4631
Revises: 86054b40fd06
Create Date: 2024-10-20 09:47:46.844436

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3897397b4631"
down_revision: str | None = "86054b40fd06"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
