"""add normalized fields to categories tags tools

Revision ID: 95f60087812f
Revises: 1d9a002d7234
Create Date: 2025-11-23 15:24:17.000000

"""

import sqlalchemy as sa
from text_unidecode import unidecode

from alembic import op

# revision identifiers, used by Alembic.
revision = "95f60087812f"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def normalize(val: str) -> str:
    """Normalize string using unidecode, matching SqlAlchemyBase.normalize"""
    return unidecode(val).lower().strip()[:255]


def populate_normalized_fields():
    bind = op.get_bind()
    BATCH_SIZE = 1_000

    def process_table(table_name):
        result = bind.execute(sa.text(f"SELECT id, name FROM {table_name} WHERE name IS NOT NULL"))

        batch = []
        for row in result:
            batch.append(
                {
                    "id": row.id,
                    "name_normalized": normalize(row.name),
                }
            )

            if len(batch) >= BATCH_SIZE:
                bind.execute(
                    sa.text(f"UPDATE {table_name} SET name_normalized = :name_normalized WHERE id = :id"),
                    batch,
                )
                batch.clear()

        if batch:
            bind.execute(
                sa.text(f"UPDATE {table_name} SET name_normalized = :name_normalized WHERE id = :id"),
                batch,
            )

        result.close()

    for table in ("categories", "tags", "tools"):
        process_table(table)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add normalized fields with server defaults first
    op.add_column("categories", sa.Column("name_normalized", sa.String(), nullable=False, server_default=""))
    op.add_column("tags", sa.Column("name_normalized", sa.String(), nullable=False, server_default=""))
    op.add_column("tools", sa.Column("name_normalized", sa.String(), nullable=False, server_default=""))

    # Create indexes
    op.create_index(op.f("ix_categories_name_normalized"), "categories", ["name_normalized"], unique=False)
    op.create_index(op.f("ix_tags_name_normalized"), "tags", ["name_normalized"], unique=False)
    op.create_index(op.f("ix_tools_name_normalized"), "tools", ["name_normalized"], unique=False)

    # Drop old indexes on name (if they exist)
    try:
        op.drop_index("ix_categories_name", table_name="categories")
    except Exception:
        pass
    try:
        op.drop_index("ix_tags_name", table_name="tags")
    except Exception:
        pass
    try:
        op.drop_index("ix_tools_name", table_name="tools")
    except Exception:
        pass

    # Populate normalized fields
    populate_normalized_fields()

    # Remove server defaults now that columns are populated
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("name_normalized", existing_type=sa.String(), server_default=None)
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.alter_column("name_normalized", existing_type=sa.String(), server_default=None)
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.alter_column("name_normalized", existing_type=sa.String(), server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tools_name_normalized"), table_name="tools")
    op.drop_index(op.f("ix_tags_name_normalized"), table_name="tags")
    op.drop_index(op.f("ix_categories_name_normalized"), table_name="categories")
    op.create_index("ix_tools_name", "tools", ["name"], unique=False)
    op.create_index("ix_tags_name", "tags", ["name"], unique=False)
    op.create_index("ix_categories_name", "categories", ["name"], unique=False)
    op.drop_column("tools", "name_normalized")
    op.drop_column("tags", "name_normalized")
    op.drop_column("categories", "name_normalized")
    # ### end Alembic commands ###
