"""add normalized fields to categories tags tools

Revision ID: 95f60087812f
Revises: 1d9a002d7234
Create Date: 2025-11-23 15:24:17.000000

"""

import sqlalchemy as sa
from sqlalchemy import orm, select
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from text_unidecode import unidecode

from alembic import op
from mealie.db.models._model_utils.guid import GUID

# revision identifiers, used by Alembic.
revision = "95f60087812f"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


class SqlAlchemyBase(DeclarativeBase):
    pass


# Intermediate table definitions
class Category(SqlAlchemyBase):
    __tablename__ = "categories"

    id: Mapped[GUID] = mapped_column(GUID, primary_key=True, default=GUID.generate)
    name: Mapped[str] = mapped_column(sa.String, nullable=False)
    name_normalized: Mapped[str] = mapped_column(sa.String, nullable=False, index=True)


class Tag(SqlAlchemyBase):
    __tablename__ = "tags"

    id: Mapped[GUID] = mapped_column(GUID, primary_key=True, default=GUID.generate)
    name: Mapped[str] = mapped_column(sa.String, nullable=False)
    name_normalized: Mapped[str] = mapped_column(sa.String, nullable=False, index=True)


class Tool(SqlAlchemyBase):
    __tablename__ = "tools"

    id: Mapped[GUID] = mapped_column(GUID, primary_key=True, default=GUID.generate)
    name: Mapped[str] = mapped_column(sa.String, nullable=False)
    name_normalized: Mapped[str] = mapped_column(sa.String, nullable=False, index=True)


def normalize(val: str) -> str:
    """Normalize string using unidecode, matching SqlAlchemyBase.normalize"""
    return unidecode(val).lower().strip()[:255]


def populate_normalized_fields():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # Populate categories
    categories = session.execute(select(Category)).scalars().all()
    for category in categories:
        if category.name is not None:
            session.execute(
                sa.text(
                    f"UPDATE {Category.__tablename__} SET name_normalized=:name_normalized WHERE id=:id"
                ).bindparams(name_normalized=normalize(category.name), id=category.id)
            )

    # Populate tags
    tags = session.execute(select(Tag)).scalars().all()
    for tag in tags:
        if tag.name is not None:
            session.execute(
                sa.text(f"UPDATE {Tag.__tablename__} SET name_normalized=:name_normalized WHERE id=:id").bindparams(
                    name_normalized=normalize(tag.name), id=tag.id
                )
            )

    # Populate tools
    tools = session.execute(select(Tool)).scalars().all()
    for tool in tools:
        if tool.name is not None:
            session.execute(
                sa.text(f"UPDATE {Tool.__tablename__} SET name_normalized=:name_normalized WHERE id=:id").bindparams(
                    name_normalized=normalize(tool.name), id=tool.id
                )
            )

    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add normalized fields with server defaults first
    op.add_column("categories", sa.Column("name_normalized", sa.String(), nullable=False, server_default=""))
    op.add_column("tags", sa.Column("name_normalized", sa.String(), nullable=False, server_default=""))
    op.add_column("tools", sa.Column("name_normalized", sa.String(), nullable=False, server_default=""))

    # Create indexes
    op.create_index(op.f("ix_categories_name_normalized"), "categories", ["name_normalized"], unique=False)
    op.create_index(op.f("ix_tags_name_normalized"), "tags", ["name_normalized"], unique=False)
    op.create_index(op.f("ix_tools_name_normalized"), "tools", ["name_normalized"], unique=False)

    # Drop old indexes on name (if they exist)
    try:
        op.drop_index("ix_categories_name", table_name="categories")
    except Exception:
        pass
    try:
        op.drop_index("ix_tags_name", table_name="tags")
    except Exception:
        pass
    try:
        op.drop_index("ix_tools_name", table_name="tools")
    except Exception:
        pass

    # Populate normalized fields
    populate_normalized_fields()

    # Remove server defaults now that columns are populated
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("name_normalized", existing_type=sa.String(), server_default=None)
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.alter_column("name_normalized", existing_type=sa.String(), server_default=None)
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.alter_column("name_normalized", existing_type=sa.String(), server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tools_name_normalized"), table_name="tools")
    op.drop_index(op.f("ix_tags_name_normalized"), table_name="tags")
    op.drop_index(op.f("ix_categories_name_normalized"), table_name="categories")
    op.create_index("ix_tools_name", "tools", ["name"], unique=False)
    op.create_index("ix_tags_name", "tags", ["name"], unique=False)
    op.create_index("ix_categories_name", "categories", ["name"], unique=False)
    op.drop_column("tools", "name_normalized")
    op.drop_column("tags", "name_normalized")
    op.drop_column("categories", "name_normalized")
    # ### end Alembic commands ###
