"""add tesco fields

Revision ID: 6887d088fc51
Revises: 1d9a002d7234
Create Date: 2025-11-23 20:31:02.771147

"""
import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = '6887d088fc51'
down_revision: str | None = '1d9a002d7234'
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tesco_product_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tesco_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tesco_unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tesco_units', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tesco_quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.drop_column('tesco_quantity')
        batch_op.drop_column('tesco_units')
        batch_op.drop_column('tesco_unit_price')
        batch_op.drop_column('tesco_price')
        batch_op.drop_column('tesco_product_url')

    # ### end Alembic commands ###
