"""'Add FDC ID and nutrition data to ingredients'

Revision ID: 5dc4387957cd
Revises: 1d9a002d7234
Create Date: 2025-12-19 12:39:25.742559

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "5dc4387957cd"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_foods_nutrition",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("food_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("fdc_nutrition_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["ingredient_foods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingredient_foods_nutrition", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingredient_foods_nutrition_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ingredient_foods_nutrition_fdc_nutrition_id"), ["fdc_nutrition_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ingredient_foods_nutrition_food_id"), ["food_id"], unique=False)

    with op.batch_alter_table("ingredient_foods", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fdc_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_foods", schema=None) as batch_op:
        batch_op.drop_column("fdc_id")

    with op.batch_alter_table("ingredient_foods_nutrition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_nutrition_food_id"))
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_nutrition_fdc_nutrition_id"))
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_nutrition_created_at"))

    op.drop_table("ingredient_foods_nutrition")
    # ### end Alembic commands ###
