"""add plural handling to group preferences

Revision ID: a8592ec31406
Revises: e6bb583aac2d
Create Date: 2025-08-22 20:11:51.875531

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8592ec31406"
down_revision: str | None = "e6bb583aac2d"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plural_handling", sa.String(), nullable=False, server_default="pluralize_food_without_unit")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_preferences", schema=None) as batch_op:
        batch_op.drop_column("plural_handling")

    # ### end Alembic commands ###
