"""add recipe translations

Revision ID: 910c8c9ed8d4
Revises: 2187537c52b8
Create Date: 2026-07-23 11:35:06.811996

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "910c8c9ed8d4"
down_revision: str | None = "2187537c52b8"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_translations",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("recipe_yield", sa.String(), nullable=True),
        sa.Column("source_hash", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "locale", name="recipe_translations_recipe_id_locale_key"),
    )
    with op.batch_alter_table("recipe_translations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_translations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_translations_locale"), ["locale"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_translations_recipe_id"), ["recipe_id"], unique=False)

    op.create_table(
        "recipe_ingredient_translations",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("translation_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("ingredient_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("original_text", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["translation_id"],
            ["recipe_translations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "translation_id", "ingredient_id", name="recipe_ingredient_translations_translation_id_ingredient_id_key"
        ),
    )
    with op.batch_alter_table("recipe_ingredient_translations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ingredient_translations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recipe_ingredient_translations_ingredient_id"), ["ingredient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recipe_ingredient_translations_translation_id"), ["translation_id"], unique=False
        )

    op.create_table(
        "recipe_instruction_translations",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("translation_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("instruction_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instruction_id"],
            ["recipe_instructions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["translation_id"],
            ["recipe_translations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "translation_id", "instruction_id", name="recipe_instruction_translations_translation_id_instruction_id_key"
        ),
    )
    with op.batch_alter_table("recipe_instruction_translations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_instruction_translations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recipe_instruction_translations_instruction_id"), ["instruction_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recipe_instruction_translations_translation_id"), ["translation_id"], unique=False
        )

    op.create_table(
        "recipe_note_translations",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("translation_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("note_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["translation_id"],
            ["recipe_translations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "translation_id", "note_index", name="recipe_note_translations_translation_id_note_index_key"
        ),
    )
    with op.batch_alter_table("recipe_note_translations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_note_translations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recipe_note_translations_translation_id"), ["translation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_note_translations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_note_translations_translation_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_note_translations_created_at"))

    op.drop_table("recipe_note_translations")
    with op.batch_alter_table("recipe_instruction_translations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_instruction_translations_translation_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_instruction_translations_instruction_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_instruction_translations_created_at"))

    op.drop_table("recipe_instruction_translations")
    with op.batch_alter_table("recipe_ingredient_translations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_ingredient_translations_translation_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingredient_translations_ingredient_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingredient_translations_created_at"))

    op.drop_table("recipe_ingredient_translations")
    with op.batch_alter_table("recipe_translations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_translations_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_translations_locale"))
        batch_op.drop_index(batch_op.f("ix_recipe_translations_created_at"))

    op.drop_table("recipe_translations")
    # ### end Alembic commands ###
