"""'Add cook time to recipe steps'

Revision ID: afdc42353aa4
Revises: b3f1c9a27d84
Create Date: 2026-09-04 16:14:42.378387

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "afdc42353aa4"
down_revision: str | None = "b3f1c9a27d84"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cook_time", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.drop_column("cook_time")

    # ### end Alembic commands ###
