"""add ingredient substitutions

Revision ID: f2191b69db2e
Revises: b3f1c9a27d84
Create Date: 2026-09-03 14:20:00.000000

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "f2191b69db2e"
down_revision: str | None = "b3f1c9a27d84"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_foods_substitutions",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("food_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("substitute_food_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.CheckConstraint("food_id != substitute_food_id", name="ingredient_foods_substitutions_no_self_substitution"),
        sa.CheckConstraint(
            "substitute_food_id IS NOT NULL OR note IS NOT NULL",
            name="ingredient_foods_substitutions_food_or_note",
        ),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["ingredient_foods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["substitute_food_id"],
            ["ingredient_foods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("food_id", "substitute_food_id", name="ingredient_foods_substitutions_food_ids_key"),
    )
    with op.batch_alter_table("ingredient_foods_substitutions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingredient_foods_substitutions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ingredient_foods_substitutions_food_id"), ["food_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ingredient_foods_substitutions_position"), ["position"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ingredient_foods_substitutions_substitute_food_id"), ["substitute_food_id"], unique=False
        )

    op.create_table(
        "recipes_ingredients_substitutions",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("substitute_food_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.CheckConstraint(
            "substitute_food_id IS NOT NULL OR note IS NOT NULL",
            name="recipes_ingredients_substitutions_food_or_note",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["recipes_ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["substitute_food_id"],
            ["ingredient_foods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipes_ingredients_substitutions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recipes_ingredients_substitutions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recipes_ingredients_substitutions_ingredient_id"), ["ingredient_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recipes_ingredients_substitutions_position"), ["position"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recipes_ingredients_substitutions_substitute_food_id"), ["substitute_food_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes_ingredients_substitutions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipes_ingredients_substitutions_substitute_food_id"))
        batch_op.drop_index(batch_op.f("ix_recipes_ingredients_substitutions_position"))
        batch_op.drop_index(batch_op.f("ix_recipes_ingredients_substitutions_ingredient_id"))
        batch_op.drop_index(batch_op.f("ix_recipes_ingredients_substitutions_created_at"))

    op.drop_table("recipes_ingredients_substitutions")
    with op.batch_alter_table("ingredient_foods_substitutions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_substitutions_substitute_food_id"))
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_substitutions_position"))
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_substitutions_food_id"))
        batch_op.drop_index(batch_op.f("ix_ingredient_foods_substitutions_created_at"))

    op.drop_table("ingredient_foods_substitutions")
    # ### end Alembic commands ###
