"""add_tag_position

Revision ID: 1f34ad247213
Revises: 3527efeeec34
Create Date: 2026-09-14 05:12:15.782114

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f34ad247213"
down_revision: str | None = "3527efeeec34"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position", sa.Integer(), server_default="2147483647", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_column("position")

    # ### end Alembic commands ###
