"""'Add mealplan updated and deleted to group notifier options'

Revision ID: cdc93edaf73d
Revises: a39c7f1826e3
Create Date: 2026-03-26 20:48:28.584661

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cdc93edaf73d"
down_revision: str | None = "a39c7f1826e3"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_events_notifier_options", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mealplan_entry_updated",
                sa.Boolean(),
                nullable=False,
                default=False,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "mealplan_entry_deleted",
                sa.Boolean(),
                nullable=False,
                default=False,
                server_default=sa.sql.expression.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_events_notifier_options", schema=None) as batch_op:
        batch_op.drop_column("mealplan_entry_deleted")
        batch_op.drop_column("mealplan_entry_updated")

    # ### end Alembic commands ###
