"""'add recipe_note_ref_link'

Revision ID: 3527efeeec34
Revises: b3f1c9a27d84
Create Date: 2026-08-29 00:03:01.424415

"""

import uuid

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "3527efeeec34"
down_revision: str | None = "b3f1c9a27d84"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_note_ref_link",
        sa.Column("instruction_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("reference_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instruction_id"],
            ["recipe_instructions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_note_ref_link", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_note_ref_link_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_note_ref_link_instruction_id"), ["instruction_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_note_ref_link_reference_id"), ["reference_id"], unique=False)

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reference_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_notes_reference_id"), ["reference_id"], unique=False)

    bind = op.get_bind()
    notes_table = sa.Table(
        "notes",
        sa.MetaData(),
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("reference_id", mealie.db.migration_types.GUID()),
    )
    note_ids = bind.execute(sa.select(notes_table.c.id)).scalars().all()
    if note_ids:
        update_stmt = notes_table.update().where(notes_table.c.id == sa.bindparam("note_id"))
        batch_params = [{"note_id": note_id, "reference_id": str(uuid.uuid4())} for note_id in note_ids]
        bind.execute(update_stmt, batch_params)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_reference_id"))
        batch_op.drop_column("reference_id")

    with op.batch_alter_table("recipe_note_ref_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_note_ref_link_reference_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_note_ref_link_instruction_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_note_ref_link_created_at"))

    op.drop_table("recipe_note_ref_link")
    # ### end Alembic commands ###
