"""'add mealplan ical token to household preferences'

Revision ID: 1e69ea7cd45e
Revises: 3527efeeec34
Create Date: 2026-09-19 16:41:13.023482

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e69ea7cd45e"
down_revision: str | None = "3527efeeec34"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("household_preferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mealplan_ical_token", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_household_preferences_mealplan_ical_token"), ["mealplan_ical_token"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("household_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_preferences_mealplan_ical_token"))
        batch_op.drop_column("mealplan_ical_token")

    # ### end Alembic commands ###
