"""'Add default shopping list'

Revision ID: daec995c3f99
Revises: b3f1c9a27d84
Create Date: 2026-09-04 15:51:38.915548

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "daec995c3f99"
down_revision: str | None = "b3f1c9a27d84"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("favorite_shopping_list_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.create_foreign_key(
            "user_favorite_shopping_list_id", "shopping_lists", ["favorite_shopping_list_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("user_favorite_shopping_list_id", type_="foreignkey")
        batch_op.drop_column("favorite_shopping_list_id")

    # ### end Alembic commands ###
