"""'Make date and entry_type nullable for meal plans without date'

Revision ID: b476454d1816
Revises: 1d9a002d7234
Create Date: 2026-02-02 21:29:38.759943

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b476454d1816"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_meal_plans", schema=None) as batch_op:
        batch_op.alter_column("date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("entry_type", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set NULL values to defaults before making non-nullable
    op.execute("UPDATE group_meal_plans SET date = CURRENT_DATE WHERE date IS NULL")
    op.execute("UPDATE group_meal_plans SET entry_type = 'dinner' WHERE entry_type IS NULL")

    with op.batch_alter_table("group_meal_plans", schema=None) as batch_op:
        batch_op.alter_column("entry_type", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("date", existing_type=sa.DATE(), nullable=False)

    # ### end Alembic commands ###
