"""'add user ip blocklist'

Revision ID: 51660002eae2
Revises: 20c3efd91432
Create Date: 2026-08-19 12:12:04.284052

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "51660002eae2"
down_revision: str | None = "20c3efd91432"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_ip_blocklist",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("created_by_user_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "ip_address", name="user_ip_blocklist_user_id_ip_address_key"),
    )
    with op.batch_alter_table("user_ip_blocklist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_ip_blocklist_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_ip_blocklist_ip_address"), ["ip_address"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_ip_blocklist_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_ip_blocklist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_ip_blocklist_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_ip_blocklist_ip_address"))
        batch_op.drop_index(batch_op.f("ix_user_ip_blocklist_created_at"))

    op.drop_table("user_ip_blocklist")
    # ### end Alembic commands ###
