"""'add username to user login history'

Revision ID: 2c84028bd4ce
Revises: 51660002eae2
Create Date: 2026-08-20 13:46:18.560995

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2c84028bd4ce"
down_revision: str | None = "51660002eae2"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_login_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_user_login_history_username"), ["username"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_login_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_login_history_username"))
        batch_op.drop_column("username")

    # ### end Alembic commands ###
