"""add locale to users

Revision ID: 0f64e4c12026
Revises: 2187537c52b8
Create Date: 2026-07-13 16:16:22.226102

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0f64e4c12026"
down_revision: str | None = "2187537c52b8"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locale", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###
