import {
  mdiAccount,
  mdiAccountCog,
  mdiAccountGroup,
  mdiAccountPlusOutline,
  mdiAlert,
  mdiAlertCircle,
  mdiAlertOutline,
  mdiApi,
  mdiArrowLeftBold,
  mdiArrowLeftBoldOutline,
  mdiArrowRightBold,
  mdiArrowRightBoldOutline,
  mdiBackupRestore,
  mdiBeakerOutline,
  mdiBellAlert,
  mdiBellPlus,
  mdiBookOpenPageVariant,
  mdiBookOutline,
  mdiBowlMixOutline,
  mdiBroom,
  mdiCalendar,
  mdiCalendarMinus,
  mdiCalendarMultiselect,
  mdiCalendarToday,
  mdiCalendarWeek,
  mdiCalendarWeekBegin,
  mdiCartCheck,
  mdiChartLine,
  mdiCheck,
  mdiCheckBold,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarkedCircle,
  mdiCheckboxOutline,
  mdiChefHat,
  mdiChevronDown,
  mdiChevronRight,
  mdiClipboardCheck,
  mdiClockTimeFourOutline,
  mdiClose,
  mdiCloudUpload,
  mdiCodeJson,
  mdiCodeTags,
  mdiCog,
  mdiCommentTextMultiple,
  mdiCommentTextMultipleOutline,
  mdiContentCopy,
  mdiContentDuplicate,
  mdiContentSave,
  mdiContentSaveEdit,
  mdiCookie,
  mdiCursorMove,
  mdiDatabase,
  mdiDelete,
  mdiDesktopTowerMonitor,
  mdiDevTo,
  mdiDiceMultiple,
  mdiDockBottom,
  mdiDockLeft,
  mdiDockRight,
  mdiDockTop,
  mdiDocker,
  mdiDotsHorizontal,
  mdiDotsVertical,
  mdiDownload,
  mdiDrag,
  mdiEmail,
  mdiEye,
  mdiEyeOff,
  mdiFile,
  mdiFileCabinet,
  mdiFileImage,
  mdiFilePdfBox,
  mdiFileSign,
  mdiFilter,
  mdiFlipHorizontal,
  mdiFlipVertical,
  mdiFolderOutline,
  mdiFolderZipOutline,
  mdiFood,
  mdiFoodApple,
  mdiFormSelect,
  mdiFormatColorFill,
  mdiFormatListChecks,
  mdiGithub,
  mdiHeart,
  mdiHeartOutline,
  mdiHelpCircleOutline,
  mdiHome,
  mdiHomeAccount,
  mdiImport,
  mdiInformation,
  mdiInformationOutline,
  mdiInformationVariant,
  mdiKnife,
  mdiLink,
  mdiLinkVariant,
  mdiLinkVariantPlus,
  mdiLock,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiMessageText,
  mdiMinus,
  mdiNewBox,
  mdiNotificationClearAll,
  mdiOpenInNew,
  mdiOrderAlphabeticalAscending,
  mdiPageLayoutBody,
  mdiPlus,
  mdiPlusCircle,
  mdiPotSteamOutline,
  mdiPrinter,
  mdiPrinterPosCog,
  mdiRefresh,
  mdiRefreshCircle,
  mdiRobot,
  mdiRotateLeft,
  mdiRotateRight,
  mdiSelectionDrag,
  mdiShapeOutline,
  mdiShareVariant,
  mdiShuffleVariant,
  mdiSilverwareForkKnife,
  mdiSilverwareVariant,
  mdiSlotMachine,
  mdiSort,
  mdiSortAlphabeticalAscending,
  mdiSortAlphabeticalDescending,
  mdiSortCalendarAscending,
  mdiSortCalendarDescending,
  mdiSortClockAscending,
  mdiSortClockDescending,
  mdiSortReverseVariant,
  mdiSortVariant,
  mdiSquareEditOutline,
  mdiStar,
  mdiTableEdit,
  mdiTagArrowRight,
  mdiTagArrowUpOutline,
  mdiTagMultipleOutline,
  mdiTestTube,
  mdiText,
  mdiTextBoxOutline,
  mdiTimelineText,
  mdiTimerSand,
  mdiTools,
  mdiTranslate,
  mdiUndo,
  mdiViewDashboard,
  mdiViewModule,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWebhook,
  mdiWindowClose,
  mdiWrench,
} from "@mdi/js";

export const icons = {
  // Primary
  primary: mdiSilverwareVariant,

  wrench: mdiWrench,
  chart: mdiChartLine,
  docker: mdiDocker,

  // General
  bowlMixOutline: mdiBowlMixOutline,
  help: mdiHelpCircleOutline,
  foods: mdiFoodApple,
  units: mdiBeakerOutline,
  alert: mdiAlert,
  alertCircle: mdiAlertCircle,
  alertOutline: mdiAlertOutline,
  api: mdiApi,
  arrowLeftBold: mdiArrowLeftBold,
  arrowRightBold: mdiArrowRightBold,
  arrowUpDown: mdiDrag,
  backupRestore: mdiBackupRestore,
  bellAlert: mdiBellAlert,
  bellPlus: mdiBellPlus,
  broom: mdiBroom,
  calendar: mdiCalendar,
  calendarMinus: mdiCalendarMinus,
  calendarMultiselect: mdiCalendarMultiselect,
  calendarToday: mdiCalendarToday,
  calendarWeek: mdiCalendarWeek,
  calendarWeekBegin: mdiCalendarWeekBegin,
  cartCheck: mdiCartCheck,
  check: mdiCheck,
  checkBold: mdiCheckBold,
  checkboxBlankOutline: mdiCheckboxBlankOutline,
  checkboxOutline: mdiCheckboxOutline,
  checkboxMarkedCircle: mdiCheckboxMarkedCircle,
  chefHat: mdiChefHat,
  clipboardCheck: mdiClipboardCheck,
  clockOutline: mdiClockTimeFourOutline,
  codeBraces: mdiCodeJson,
  codeJson: mdiCodeJson,
  codeTags: mdiCodeTags,
  cog: mdiCog,
  commentTextMultiple: mdiCommentTextMultiple,
  commentTextMultipleOutline: mdiCommentTextMultipleOutline,
  contentCopy: mdiContentCopy,
  database: mdiDatabase,
  desktopTowerMonitor: mdiDesktopTowerMonitor,
  devTo: mdiDevTo,
  knife: mdiKnife,
  diceMultiple: mdiDiceMultiple,
  dockTop: mdiDockTop,
  dockBottom: mdiDockBottom,
  dockLeft: mdiDockLeft,
  dockRight: mdiDockRight,
  dotsHorizontal: mdiDotsHorizontal,
  dotsVertical: mdiDotsVertical,
  download: mdiDownload,
  duplicate: mdiContentDuplicate,
  email: mdiEmail,
  externalLink: mdiLinkVariant,
  eye: mdiEye,
  eyeOff: mdiEyeOff,
  file: mdiFile,
  fileImage: mdiFileImage,
  filePDF: mdiFilePdfBox,
  filter: mdiFilter,
  flipHorizontal: mdiFlipHorizontal,
  flipVertical: mdiFlipVertical,
  folderOutline: mdiFolderOutline,
  food: mdiFood,
  formatColorFill: mdiFormatColorFill,
  formatListCheck: mdiFormatListChecks,
  formSelect: mdiFormSelect,
  github: mdiGithub,
  heart: mdiHeart,
  heartOutline: mdiHeartOutline,
  home: mdiHome,
  household: mdiHomeAccount,
  import: mdiImport,
  information: mdiInformation,
  informationOutline: mdiInformationOutline,
  informationVariant: mdiInformationVariant,
  link: mdiLink,
  linkVariantPlus: mdiLinkVariantPlus,
  lock: mdiLock,
  logout: mdiLogout,
  manageData: mdiTableEdit,
  menu: mdiMenu,
  messageText: mdiMessageText,
  newBox: mdiNewBox,
  notificationClearAll: mdiNotificationClearAll,
  openInNew: mdiOpenInNew,
  orderAlphabeticalAscending: mdiOrderAlphabeticalAscending,
  pageLayoutBody: mdiPageLayoutBody,
  printer: mdiPrinter,
  printerSettings: mdiPrinterPosCog,
  refreshCircle: mdiRefreshCircle,
  robot: mdiRobot,
  rotateLeft: mdiRotateLeft,
  rotateRight: mdiRotateRight,
  search: mdiMagnify,
  shareVariant: mdiShareVariant,
  shuffleVariant: mdiShuffleVariant,
  silverwareForkKnife: mdiSilverwareForkKnife,
  sort: mdiSort,
  sortAscending: mdiSortVariant,
  sortDescending: mdiSortReverseVariant,
  sortAlphabeticalAscending: mdiSortAlphabeticalAscending,
  sortAlphabeticalDescending: mdiSortAlphabeticalDescending,
  sortCalendarAscending: mdiSortCalendarAscending,
  sortCalendarDescending: mdiSortCalendarDescending,
  sortClockAscending: mdiSortClockAscending,
  sortClockDescending: mdiSortClockDescending,
  star: mdiStar,
  testTube: mdiTestTube,
  timelineText: mdiTimelineText,
  tools: mdiTools,
  potSteam: mdiPotSteamOutline,
  translate: mdiTranslate,
  upload: mdiCloudUpload,
  viewDashboard: mdiViewDashboard,
  viewModule: mdiViewModule,
  weatherNight: mdiWeatherNight,
  weatherSunny: mdiWeatherSunny,
  webhook: mdiWebhook,
  windowClose: mdiWindowClose,
  zip: mdiFolderZipOutline,
  undo: mdiUndo,
  bread: mdiCookie,
  fileSign: mdiFileSign,

  // Crud
  backArrow: mdiArrowLeftBoldOutline,
  createAlt: mdiPlus,
  create: mdiPlusCircle,
  delete: mdiDelete,
  save: mdiContentSave,
  update: mdiContentSaveEdit,
  edit: mdiSquareEditOutline,
  close: mdiClose,
  minus: mdiMinus,
  pending: mdiTimerSand,
  refresh: mdiRefresh,

  // Organization
  tags: mdiTagMultipleOutline,
  tagArrowUp: mdiTagArrowUpOutline,
  tagArrowRight: mdiTagArrowRight,
  categories: mdiShapeOutline,
  pages: mdiBookOutline,
  book: mdiBookOpenPageVariant,
  organizers: mdiFileCabinet,

  // Admin
  user: mdiAccount,
  admin: mdiAccountCog,
  group: mdiAccountGroup,
  accountPlusOutline: mdiAccountPlusOutline,

  forward: mdiArrowRightBoldOutline,
  back: mdiArrowLeftBoldOutline,
  slotMachine: mdiSlotMachine,
  chevronDown: mdiChevronDown,
  chevronRight: mdiChevronRight,

  // Ocr toolbar
  selectMode: mdiSelectionDrag,
  panAndZoom: mdiCursorMove,
  preserveLines: mdiText,
  preserveBlocks: mdiTextBoxOutline,
  flatten: mdiMinus,
};
