from dataclasses import dataclass


@dataclass
class ErrorMessages:
    """
    This enum class holds the text values that represent the errors returned when
    something goes wrong on the server side.

    Example: {"details": "general-failure"}

    The items contained within the '#' are automatically generated by a script in the scripts directory.
    DO NOT EDIT THE CONTENTS BETWEEN THOSE. If you need to add a custom error message, do so in the lines
    above.

    Why Generate This!?!?! If we generate static errors on the backend we can ensure that a constant
    set or error messages will be returned to the frontend. As such we can use the "details" key to
    look up localized messages in the frontend. as such DO NOT change the generated or manual codes
    without making the necessary changes on the client side code.
    """

    general_failure = "general-failure"

    # CODE_GEN_ID: ERROR_MESSAGE_ENUMS
    backup_create_failure = "backup-create-failure"
    backup_update_failure = "backup-update-failure"
    backup_delete_failure = "backup-delete-failure"

    cookbook_create_failure = "cookbook-create-failure"
    cookbook_update_failure = "cookbook-update-failure"
    cookbook_delete_failure = "cookbook-delete-failure"

    event_create_failure = "event-create-failure"
    event_update_failure = "event-update-failure"
    event_delete_failure = "event-delete-failure"

    food_create_failure = "food-create-failure"
    food_update_failure = "food-update-failure"
    food_delete_failure = "food-delete-failure"

    group_create_failure = "group-create-failure"
    group_update_failure = "group-update-failure"
    group_delete_failure = "group-delete-failure"

    ingredient_create_failure = "ingredient-create-failure"
    ingredient_update_failure = "ingredient-update-failure"
    ingredient_delete_failure = "ingredient-delete-failure"

    mealplan_create_failure = "mealplan-create-failure"
    mealplan_update_failure = "mealplan-update-failure"
    mealplan_delete_failure = "mealplan-delete-failure"

    migration_create_failure = "migration-create-failure"
    migration_update_failure = "migration-update-failure"
    migration_delete_failure = "migration-delete-failure"

    recipe_create_failure = "recipe-create-failure"
    recipe_update_failure = "recipe-update-failure"
    recipe_delete_failure = "recipe-delete-failure"

    scraper_create_failure = "scraper-create-failure"
    scraper_update_failure = "scraper-update-failure"
    scraper_delete_failure = "scraper-delete-failure"

    token_create_failure = "token-create-failure"
    token_update_failure = "token-update-failure"
    token_delete_failure = "token-delete-failure"

    unit_create_failure = "unit-create-failure"
    unit_update_failure = "unit-update-failure"
    unit_delete_failure = "unit-delete-failure"

    user_create_failure = "user-create-failure"
    user_update_failure = "user-update-failure"
    user_delete_failure = "user-delete-failure"

    webhook_create_failure = "webhook-create-failure"
    webhook_update_failure = "webhook-update-failure"
    webhook_delete_failure = "webhook-delete-failure"

    # END ERROR_MESSAGE_ENUMS
