version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - hay-kot
    assignees:
      - hay-kot
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/frontend"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - hay-kot
    assignees:
      - hay-kot
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: pip
    directory: "/mealie"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - hay-kot
    assignees:
      - hay-kot
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
