preserve_hierarchy: false
files:
  - source: /frontend/lang/messages/en-US.json
    translation: /frontend/lang/messages/%locale%.json
  - source: /mealie/lang/messages/en-US.json
    translation: /mealie/lang/messages/%locale%.json
  - source: /mealie/repos/seed/resources/foods/locales/en-US.json
    translation: /mealie/repos/seed/resources/foods/locales/%locale%.json
  - source: /mealie/repos/seed/resources/units/locales/en-US.json
    translation: /mealie/repos/seed/resources/units/locales/%locale%.json
  - source: /mealie/repos/seed/resources/labels/locales/en-US.json
    translation: /mealie/repos/seed/resources/labels/locales/%locale%.json
