preserve_hierarchy: false
files:
  - source: /frontend/src/locales/messages/en-US.json
    translation: /frontend/src/locales/messages/%locale%.json
  - source: /frontend/src/locales/dateTimeFormats/en-US.json
    translation: /frontend/src/locales/dateTimeFormats/%locale%.json

  # Backend General Messages
  - source: /mealie/lang/messages/en-US.json
    translation: /mealie/lang/messages/%locale%.json

  # Resource Files
  - source: /mealie/repos/seed/resources/foods/locales/en-US.json
    translation: /mealie/repos/seed/resources/foods/locales/%locale%.json
  - source: /mealie/repos/seed/resources/units/locales/en-US.json
    translation: /mealie/repos/seed/resources/units/locales/%locale%.json
  - source: /mealie/repos/seed/resources/labels/locales/en-US.json
    translation: /mealie/repos/seed/resources/labels/locales/%locale%.json
