FROM python:3.9-buster

ENV PRODUCTION false
ENV POETRY_VERSION 1.1.6

# poetry
RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"

# database drivers
RUN pip install --no-cache-dir "psycopg2-binary==2.8.6"

# project dependencies
WORKDIR /app
COPY pyproject.toml poetry.lock /app/
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev --no-interaction --no-ansi

# project code
COPY ./mealie /app/mealie
COPY ./alembic /app/alembic
COPY alembic.ini /app

CMD [ "/app/mealie/run.sh", "development" ]
