services:
  mealie:
    image: localhost/mealie:dev
    container_name: mealie
    restart: always
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      OPENAI_BASE_URL: http://10.10.0.31:4000
      OPENAI_API_KEY: sk-Sz2zvLHZj470KecTe4rPTA
      OPENAI_MODEL: gemini/gemini-2.0-flash
    networks:
      - default
networks: {}
volumes:
  mealie-data:
