[build]
publish = "docs/site/"
command = """
pip3 install mkdocs-material &&
cd docs &&
mkdocs build
"""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
