[build]
publish = "docs/site/"
command = """
pip3 install zensical==0.0.57 &&
cd docs &&
zensical build
"""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
