---
title: OAuth setup with <PROVIDER>
body:
- type: textarea
  attributes:
    label: Configuration Example
    description: Add your example configuration. You can provide code blocks, screenshots, and links.
  validations:
    required: true
