apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-app
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-app
  template:
    metadata:
      labels:
        app: mealie-app
    spec:
      containers:
        - name: mealie
          image: proj18biasvariance/mealie-custom:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          startupProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_SERVER
              value: postgres.platform.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: mealie
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: INFERENCE_API_URL
              value: "http://inference-service.serving.svc.cluster.local:8000"
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  namespace: mealie
spec:
  type: NodePort
  selector:
    app: mealie-app
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090
