// This Code is auto generated by gen_global_components.py
 import BaseCardSectionTitle from "@/components/global/BaseCardSectionTitle.vue";
 import MarkdownEditor from "@/components/global/MarkdownEditor.vue";
 import AppLoader from "@/components/global/AppLoader.vue";
 import BaseOverflowButton from "@/components/global/BaseOverflowButton.vue";
 import ReportTable from "@/components/global/ReportTable.vue";
 import AppToolbar from "@/components/global/AppToolbar.vue";
 import BaseButtonGroup from "@/components/global/BaseButtonGroup.vue";
 import BaseButton from "@/components/global/BaseButton.vue";
 import BannerExperimental from "@/components/global/BannerExperimental.vue";
 import BaseDialog from "@/components/global/BaseDialog.vue";
 import RecipeJsonEditor from "@/components/global/RecipeJsonEditor.vue";
 import BaseStatCard from "@/components/global/BaseStatCard.vue";
 import DevDumpJson from "@/components/global/DevDumpJson.vue";
 import InputQuantity from "@/components/global/InputQuantity.vue";
 import ToggleState from "@/components/global/ToggleState.vue";
 import AppButtonCopy from "@/components/global/AppButtonCopy.vue";
 import InputColor from "@/components/global/InputColor.vue";
 import BaseDivider from "@/components/global/BaseDivider.vue";
 import AutoForm from "@/components/global/AutoForm.vue";
 import AppButtonUpload from "@/components/global/AppButtonUpload.vue";
 import BasePageTitle from "@/components/global/BasePageTitle.vue";
 import ButtonLink from "@/components/global/ButtonLink.vue";

 import TheSnackbar from "@/components/layout/TheSnackbar.vue";
 import AppHeader from "@/components/layout/AppHeader.vue";
 import AppSidebar from "@/components/layout/AppSidebar.vue";
 import AppFooter from "@/components/layout/AppFooter.vue";


declare module "vue" {
  export interface GlobalComponents {
    // Global Components
     BaseCardSectionTitle: typeof BaseCardSectionTitle;
     MarkdownEditor: typeof MarkdownEditor;
     AppLoader: typeof AppLoader;
     BaseOverflowButton: typeof BaseOverflowButton;
     ReportTable: typeof ReportTable;
     AppToolbar: typeof AppToolbar;
     BaseButtonGroup: typeof BaseButtonGroup;
     BaseButton: typeof BaseButton;
     BannerExperimental: typeof BannerExperimental;
     BaseDialog: typeof BaseDialog;
     RecipeJsonEditor: typeof RecipeJsonEditor;
     BaseStatCard: typeof BaseStatCard;
     DevDumpJson: typeof DevDumpJson;
     InputQuantity: typeof InputQuantity;
     ToggleState: typeof ToggleState;
     AppButtonCopy: typeof AppButtonCopy;
     InputColor: typeof InputColor;
     BaseDivider: typeof BaseDivider;
     AutoForm: typeof AutoForm;
     AppButtonUpload: typeof AppButtonUpload;
     BasePageTitle: typeof BasePageTitle;
     ButtonLink: typeof ButtonLink;
     // Layout Components
     TheSnackbar: typeof TheSnackbar;
     AppHeader: typeof AppHeader;
     AppSidebar: typeof AppSidebar;
     AppFooter: typeof AppFooter;
    
  }
}

export {};