export interface Icon {
  // Primary
  primary: String;

  // General
  foods: String;
  units: String;
  alert: String;
  alertCircle: String;
  api: String;
  arrowLeftBold: String;
  arrowUpDown: String;
  backupRestore: String;
  bellAlert: String;
  broom: String;
  calendar: String;
  calendarMinus: String;
  calendarMultiselect: String;
  calendarToday: String;
  calendarWeek: String;
  calendarWeekBegin: String;
  cartCheck: String;
  check: String;
  checkboxBlankOutline: String;
  checkboxMarkedCircle: String;
  clipboardCheck: String;
  clockOutline: String;
  codeBraces: String;
  codeJson: String;
  cog: String;
  commentTextMultipleOutline: String;
  contentCopy: String;
  database: String;
  desktopTowerMonitor: String;
  devTo: String;
  diceMultiple: String;
  dotsHorizontal: String;
  dotsVertical: String;
  download: String;
  email: String;
  externalLink: String;
  eye: String;
  eyeOff: String;
  file: String;
  fileImage: String;
  filePDF: String;
  filter: String;
  folderOutline: String;
  food: String;
  formatColorFill: String;
  formatListCheck: String;
  formSelect: String;
  github: String;
  heart: String;
  heartOutline: String;
  home: String;
  import: String;
  information: String;
  link: String;
  lock: String;
  logout: String;
  menu: String;
  newBox: String;
  notificationClearAll: String;
  openInNew: String;
  orderAlphabeticalAscending: String;
  pageLayoutBody: String;
  printer: String;
  refreshCircle: String;
  robot: String;
  search: String;
  shareVariant: String;
  shuffleVariant: String;
  sort: String;
  star: String;
  testTube: String;
  tools: String;
  translate: String;
  upload: String;
  viewDashboard: String;
  viewModule: String;
  weatherNight: String;
  weatherSunny: String;
  webhook: String;
  windowClose: String;
  zip: String;

  // Crud
  backArrow: String;
  createAlt: String;
  create: String;
  delete: String;
  save: String;
  update: String;
  edit: String;
  close: String;
  minus: String;

  // Organization
  tags: String;
  pages: String;

  // Admin
  user: String;
  admin: String;
  group: String;
  accountPlusOutline: String;

  forward: String;
  back: String;
}
