export interface Icon {
  // Primary
  primary: string;

  // General
  chart: string;
  wrench: string;
  help: string;
  bowlMixOutline: string;
  foods: string;
  units: string;
  alert: string;
  alertCircle: string;
  api: string;
  arrowLeftBold: string;
  arrowUpDown: string;
  backupRestore: string;
  bellAlert: string;
  broom: string;
  calendar: string;
  calendarMinus: string;
  calendarMultiselect: string;
  calendarToday: string;
  calendarWeek: string;
  calendarWeekBegin: string;
  cartCheck: string;
  check: string;
  checkboxBlankOutline: string;
  checkboxMarkedCircle: string;
  clipboardCheck: string;
  clockOutline: string;
  codeBraces: string;
  codeJson: string;
  cog: string;
  commentTextMultipleOutline: string;
  contentCopy: string;
  database: string;
  desktopTowerMonitor: string;
  devTo: string;
  diceMultiple: string;
  dotsHorizontal: string;
  dotsVertical: string;
  download: string;
  email: string;
  externalLink: string;
  eye: string;
  eyeOff: string;
  file: string;
  fileImage: string;
  filePDF: string;
  filter: string;
  folderOutline: string;
  food: string;
  formatColorFill: string;
  formatListCheck: string;
  formSelect: string;
  github: string;
  heart: string;
  heartOutline: string;
  home: string;
  import: string;
  information: string;
  link: string;
  lock: string;
  logout: string;
  menu: string;
  newBox: string;
  notificationClearAll: string;
  openInNew: string;
  orderAlphabeticalAscending: string;
  pageLayoutBody: string;
  potSteam: string;
  printer: string;
  refreshCircle: string;
  robot: string;
  search: string;
  shareVariant: string;
  shuffleVariant: string;
  sort: string;
  star: string;
  testTube: string;
  tools: string;
  translate: string;
  upload: string;
  viewDashboard: string;
  viewModule: string;
  weatherNight: string;
  weatherSunny: string;
  webhook: string;
  windowClose: string;
  zip: string;

  // Crud
  backArrow: string;
  createAlt: string;
  create: string;
  delete: string;
  save: string;
  update: string;
  edit: string;
  close: string;
  minus: string;

  // Organization
  tags: string;
  pages: string;

  // Admin
  user: string;
  admin: string;
  group: string;
  accountPlusOutline: string;

  forward: string;
  back: string;
  slotMachine: string;
  chevronDown: string;
}
