// This Code is auto generated by gen_ts_types.py
import type AdvancedOnly from "@/components/global/AdvancedOnly.vue";
import type AppButtonCopy from "@/components/global/AppButtonCopy.vue";
import type AppButtonUpload from "@/components/global/AppButtonUpload.vue";
import type AppLoader from "@/components/global/AppLoader.vue";
import type AppLogo from "@/components/global/AppLogo.vue";
import type AppToolbar from "@/components/global/AppToolbar.vue";
import type AutoForm from "@/components/global/AutoForm.vue";
import type BannerExperimental from "@/components/global/BannerExperimental.vue";
import type BannerWarning from "@/components/global/BannerWarning.vue";
import type BaseButton from "@/components/global/BaseButton.vue";
import type BaseButtonGroup from "@/components/global/BaseButtonGroup.vue";
import type BaseCardSectionTitle from "@/components/global/BaseCardSectionTitle.vue";
import type BaseDialog from "@/components/global/BaseDialog.vue";
import type BaseDivider from "@/components/global/BaseDivider.vue";
import type BaseExpansionPanels from "@/components/global/BaseExpansionPanels.vue";
import type BaseOverflowButton from "@/components/global/BaseOverflowButton.vue";
import type BasePageTitle from "@/components/global/BasePageTitle.vue";
import type BaseStatCard from "@/components/global/BaseStatCard.vue";
import type ButtonLink from "@/components/global/ButtonLink.vue";
import type ContextMenu from "@/components/global/ContextMenu.vue";
import type CrudTable from "@/components/global/CrudTable.vue";
import type DevDumpJson from "@/components/global/DevDumpJson.vue";
import type DocLink from "@/components/global/DocLink.vue";
import type DropZone from "@/components/global/DropZone.vue";
import type HelpIcon from "@/components/global/HelpIcon.vue";
import type ImageCropper from "@/components/global/ImageCropper.vue";
import type InputColor from "@/components/global/InputColor.vue";
import type InputLabelType from "@/components/global/InputLabelType.vue";
import type LanguageDialog from "@/components/global/LanguageDialog.vue";
import type MarkdownEditor from "@/components/global/MarkdownEditor.vue";
import type RecipeJsonEditor from "@/components/global/RecipeJsonEditor.vue";
import type ReportTable from "@/components/global/ReportTable.vue";
import type SafeMarkdown from "@/components/global/SafeMarkdown.vue";
import type StatsCards from "@/components/global/StatsCards.vue";
import type ToggleState from "@/components/global/ToggleState.vue";
import type WakelockSwitch from "@/components/global/WakelockSwitch.vue";
import type DefaultLayout from "@/components/layout/DefaultLayout.vue";

declare module "vue" {
  export interface GlobalComponents {
    // Global Components
    AdvancedOnly: typeof AdvancedOnly;
    AppButtonCopy: typeof AppButtonCopy;
    AppButtonUpload: typeof AppButtonUpload;
    AppLoader: typeof AppLoader;
    AppLogo: typeof AppLogo;
    AppToolbar: typeof AppToolbar;
    AutoForm: typeof AutoForm;
    BannerExperimental: typeof BannerExperimental;
    BannerWarning: typeof BannerWarning;
    BaseButton: typeof BaseButton;
    BaseButtonGroup: typeof BaseButtonGroup;
    BaseCardSectionTitle: typeof BaseCardSectionTitle;
    BaseDialog: typeof BaseDialog;
    BaseDivider: typeof BaseDivider;
    BaseExpansionPanels: typeof BaseExpansionPanels;
    BaseOverflowButton: typeof BaseOverflowButton;
    BasePageTitle: typeof BasePageTitle;
    BaseStatCard: typeof BaseStatCard;
    ButtonLink: typeof ButtonLink;
    ContextMenu: typeof ContextMenu;
    CrudTable: typeof CrudTable;
    DevDumpJson: typeof DevDumpJson;
    DocLink: typeof DocLink;
    DropZone: typeof DropZone;
    HelpIcon: typeof HelpIcon;
    ImageCropper: typeof ImageCropper;
    InputColor: typeof InputColor;
    InputLabelType: typeof InputLabelType;
    LanguageDialog: typeof LanguageDialog;
    MarkdownEditor: typeof MarkdownEditor;
    RecipeJsonEditor: typeof RecipeJsonEditor;
    ReportTable: typeof ReportTable;
    SafeMarkdown: typeof SafeMarkdown;
    StatsCards: typeof StatsCards;
    ToggleState: typeof ToggleState;
    WakelockSwitch: typeof WakelockSwitch;
    // Layout Components
    DefaultLayout: typeof DefaultLayout;
  }
}

export {};
