<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AiController;
use App\Http\Controllers\AppController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\ExploreController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HouseholdController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\OpsController;
use App\Http\Controllers\ParserController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\RecipeController;
use App\Services\OpsService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/health', HealthController::class);

Route::get('/auth/oauth', [AuthController::class, 'oauth']);
Route::get('/auth/oauth/callback', [AuthController::class, 'oauth']);
Route::post('/auth/oauth/callback', [AuthController::class, 'oauth']);
Route::post('/auth/token', [AuthController::class, 'token']);
Route::post('/auth/logout', [AuthController::class, 'logout']);
Route::get('/app/about', [AppController::class, 'about']);
Route::get('/app/startup-info', [AppController::class, 'startup']);
Route::get('/app/theme', [AppController::class, 'theme']);
Route::post('/users/register', [AccountController::class, 'register']);
Route::post('/users/forgot-password', [AccountController::class, 'forgotPassword']);
Route::post('/users/reset-password', [AccountController::class, 'resetPassword']);
Route::get('/explore/groups/{groupSlug}/recipes', [ExploreController::class, 'recipes']);
Route::get('/explore/groups/{groupSlug}/recipes/{recipeSlug}', [ExploreController::class, 'recipe']);
Route::get('/explore/groups/{groupSlug}/organizers/categories', [ExploreController::class, 'categories']);
Route::get('/explore/groups/{groupSlug}/organizers/tags', [ExploreController::class, 'tags']);
Route::get('/explore/groups/{groupSlug}/organizers/tools', [ExploreController::class, 'tools']);
Route::get('/explore/groups/{groupSlug}/households', [ExploreController::class, 'households']);
Route::get('/explore/groups/{groupSlug}/foods', [ExploreController::class, 'foods']);
Route::get('/explore/groups/{groupSlug}/households/{householdSlug}/cookbooks', [ExploreController::class, 'cookbooks']);
Route::get('/recipes/shared/{token}/zip', [RecipeController::class, 'sharedZip']);
Route::get('/recipes/shared/{token}', [RecipeController::class, 'shared']);
Route::get('/validators/user/name', fn (Request $request) => response()->json(app(OpsService::class)->validateUnique('users', 'username', (string) $request->query('name', ''))));
Route::get('/validators/user/email', fn (Request $request) => response()->json(app(OpsService::class)->validateUnique('users', 'email', (string) $request->query('email', ''))));
Route::get('/validators/group', fn (Request $request) => response()->json(app(OpsService::class)->validateUnique('groups', 'name', (string) $request->query('name', ''))));
Route::get('/validators/household', fn (Request $request) => response()->json(app(OpsService::class)->validateUnique('households', 'name', (string) $request->query('name', ''))));
Route::get('/media/recipes/{recipeId}/images/timeline/{eventId}/{fileName}', [MediaController::class, 'timelineImage']);
Route::get('/media/recipes/{recipeId}/images/{fileName}', [MediaController::class, 'recipeImage']);
Route::get('/media/users/{userId}/{fileName}', [MediaController::class, 'userImage']);

Route::middleware('mealie.auth')->group(function () {
    Route::post('/auth/refresh', [AuthController::class, 'refresh']);

    Route::get('/users/self', [AccountController::class, 'self']);
    Route::put('/users/self', [AccountController::class, 'updateSelf']);
    Route::get('/users/api-tokens', [AccountController::class, 'tokens']);
    Route::post('/users/api-tokens', [AccountController::class, 'storeToken']);
    Route::delete('/users/api-tokens/{id}', [AccountController::class, 'destroyToken']);
    Route::put('/households/permissions', [AccountController::class, 'permissions']);
    Route::get('/users/self/ratings', [AccountController::class, 'ratings']);
    Route::get('/users/self/favorites', [AccountController::class, 'favorites']);
    Route::put('/users/password', [AccountController::class, 'password']);
    Route::post('/users/{id}/image', [AccountController::class, 'uploadImage']);
    Route::post('/users/{id}/ratings/{slug}', [AccountController::class, 'setRating']);
    Route::post('/users/{id}/favorites/{slug}', [AccountController::class, 'favorite']);
    Route::delete('/users/{id}/favorites/{slug}', [AccountController::class, 'unfavorite']);

    Route::get('/groups/self', [AccountController::class, 'group']);
    Route::get('/groups/preferences', [AccountController::class, 'groupPreferences']);
    Route::put('/groups/preferences', [AccountController::class, 'updateGroupPreferences']);
    Route::get('/groups/members', [AccountController::class, 'groupMembers']);
    Route::get('/households/self', [AccountController::class, 'household']);
    Route::get('/households/members', [AccountController::class, 'householdMembers']);
    Route::get('/households/preferences', [AccountController::class, 'householdPreferences']);
    Route::put('/households/preferences', [AccountController::class, 'updateHouseholdPreferences']);
    Route::get('/households/statistics', [AccountController::class, 'householdStatistics']);

    Route::get('/recipes', [RecipeController::class, 'index']);
    Route::get('/recipes/suggestions', [RecipeController::class, 'suggestions']);
    Route::post('/recipes/create', [RecipeController::class, 'store']);
    Route::post('/recipes/create/url', [RecipeController::class, 'importUrl']);
    Route::post('/recipes/create/url/stream', [RecipeController::class, 'importUrl']);
    Route::post('/recipes/create/url/bulk', [RecipeController::class, 'importBulk']);
    Route::post('/recipes/create/ai/stream', [RecipeController::class, 'importAi']);
    Route::post('/recipes/create/html-or-json/stream', [RecipeController::class, 'importDocument']);
    Route::post('/recipes/test-scrape-url', [RecipeController::class, 'testScrape']);
    Route::post('/recipes/bulk-actions/{action}', [RecipeController::class, 'bulk']);
    Route::get('/recipes/timeline/events', [HouseholdController::class, 'timeline']);
    Route::post('/recipes/timeline/events', [HouseholdController::class, 'storeTimeline']);
    Route::put('/recipes/timeline/events/{id}', [HouseholdController::class, 'updateTimeline']);
    Route::post('/recipes/timeline/events/{id}/image', [HouseholdController::class, 'uploadTimelineImage']);
    Route::delete('/recipes/timeline/events/{id}', [HouseholdController::class, 'destroyTimeline']);
    Route::get('/groups/ai-providers/settings', [AiController::class, 'settings']);
    Route::put('/groups/ai-providers/settings', [AiController::class, 'updateSettings']);
    Route::get('/groups/ai-providers/providers', [AiController::class, 'providers']);
    Route::post('/groups/ai-providers/providers', [AiController::class, 'storeProvider']);
    Route::post('/groups/ai-providers/providers/test', [AiController::class, 'test']);
    Route::get('/groups/ai-providers/providers/{id}', [AiController::class, 'provider']);
    Route::put('/groups/ai-providers/providers/{id}', [AiController::class, 'updateProvider']);
    Route::delete('/groups/ai-providers/providers/{id}', [AiController::class, 'destroyProvider']);
    Route::put('/recipes/{slug}/image', [RecipeController::class, 'uploadImage']);
    Route::delete('/recipes/{slug}/image', [RecipeController::class, 'deleteImage']);
    Route::patch('/recipes/{slug}/last-made', [RecipeController::class, 'lastMade']);
    Route::post('/recipes/{slug}/duplicate', [RecipeController::class, 'duplicate']);
    Route::get('/recipes/{slug}/assets', [RecipeController::class, 'assets']);
    Route::post('/recipes/{slug}/assets', [RecipeController::class, 'storeAsset']);
    Route::get('/recipes/{slug}/comments', [RecipeController::class, 'comments']);
    Route::post('/recipes/{slug}/comments', [RecipeController::class, 'storeComment']);
    Route::get('/recipes/{slug}', [RecipeController::class, 'show']);
    Route::put('/recipes/{slug}', [RecipeController::class, 'update']);
    Route::patch('/recipes/{slug}', [RecipeController::class, 'update']);
    Route::delete('/recipes/{slug}', [RecipeController::class, 'destroy']);

    Route::get('/categories/empty', [CatalogController::class, 'emptyCategories']);
    Route::post('/categories/merge', [CatalogController::class, 'mergeCategories']);
    Route::get('/categories/slug/{slug}', [CatalogController::class, 'categorySlug']);
    Route::get('/categories', [CatalogController::class, 'categories']);
    Route::post('/categories', [CatalogController::class, 'storeCategory']);
    Route::put('/categories/{id}', [CatalogController::class, 'updateCategory']);
    Route::delete('/categories/{id}', [CatalogController::class, 'destroyCategory']);
    Route::get('/tags/empty', [CatalogController::class, 'emptyTags']);
    Route::post('/tags/merge', [CatalogController::class, 'mergeTags']);
    Route::get('/tags/slug/{slug}', [CatalogController::class, 'tagSlug']);
    Route::get('/tags', [CatalogController::class, 'tags']);
    Route::post('/tags', [CatalogController::class, 'storeTag']);
    Route::put('/tags/{id}', [CatalogController::class, 'updateTag']);
    Route::delete('/tags/{id}', [CatalogController::class, 'destroyTag']);
    Route::get('/tools/slug/{slug}', [CatalogController::class, 'toolSlug']);
    Route::get('/tools', [CatalogController::class, 'tools']);
    Route::post('/tools', [CatalogController::class, 'storeTool']);
    Route::put('/tools/{id}', [CatalogController::class, 'updateTool']);
    Route::delete('/tools/{id}', [CatalogController::class, 'destroyTool']);
    Route::post('/foods/merge', [CatalogController::class, 'mergeFoods']);
    Route::get('/foods/{id}', [CatalogController::class, 'showFood']);
    Route::get('/foods', [CatalogController::class, 'foods']);
    Route::post('/foods', [CatalogController::class, 'storeFood']);
    Route::put('/foods/{id}', [CatalogController::class, 'updateFood']);
    Route::delete('/foods/{id}', [CatalogController::class, 'destroyFood']);
    Route::post('/units/merge', [CatalogController::class, 'mergeUnits']);
    Route::get('/units/{id}', [CatalogController::class, 'showUnit']);
    Route::get('/units', [CatalogController::class, 'units']);
    Route::post('/units', [CatalogController::class, 'storeUnit']);
    Route::put('/units/{id}', [CatalogController::class, 'updateUnit']);
    Route::delete('/units/{id}', [CatalogController::class, 'destroyUnit']);
    Route::get('/groups/labels', [CatalogController::class, 'labels']);
    Route::post('/groups/labels', [CatalogController::class, 'storeLabel']);
    Route::put('/groups/labels/{id}', [CatalogController::class, 'updateLabel']);
    Route::delete('/groups/labels/{id}', [CatalogController::class, 'destroyLabel']);
    Route::get('/households/cookbooks', [CatalogController::class, 'cookbooks']);
    Route::post('/households/cookbooks', [CatalogController::class, 'storeCookbook']);
    Route::put('/households/cookbooks/{id}', [CatalogController::class, 'updateCookbook']);
    Route::delete('/households/cookbooks/{id}', [CatalogController::class, 'destroyCookbook']);

    Route::get('/comments', [RecipeController::class, 'commentIndex']);
    Route::put('/comments/{id}', [RecipeController::class, 'updateComment']);
    Route::delete('/comments/{id}', [RecipeController::class, 'destroyComment']);
    Route::get('/shared/recipes', [RecipeController::class, 'shares']);
    Route::post('/shared/recipes', [RecipeController::class, 'storeShare']);
    Route::get('/shared/recipes/{id}', [RecipeController::class, 'share']);
    Route::delete('/shared/recipes/{id}', [RecipeController::class, 'destroyShare']);

    Route::get('/households/mealplans/rules', [PlanController::class, 'rules']);
    Route::post('/households/mealplans/rules', [PlanController::class, 'storeRule']);
    Route::put('/households/mealplans/rules/{itemId}', [PlanController::class, 'updateRule']);
    Route::delete('/households/mealplans/rules/{itemId}', [PlanController::class, 'destroyRule']);
    Route::get('/households/mealplans/today', [PlanController::class, 'today']);
    Route::post('/households/mealplans/random', [PlanController::class, 'random']);
    Route::get('/households/mealplans', [PlanController::class, 'mealPlans']);
    Route::post('/households/mealplans', [PlanController::class, 'storeMealPlan']);
    Route::put('/households/mealplans/{itemId}', [PlanController::class, 'updateMealPlan']);
    Route::delete('/households/mealplans/{itemId}', [PlanController::class, 'destroyMealPlan']);
    Route::get('/households/shopping/lists', [PlanController::class, 'shoppingLists']);
    Route::post('/households/shopping/lists', [PlanController::class, 'storeShoppingList']);
    Route::put('/households/shopping/lists/{itemId}', [PlanController::class, 'updateShoppingList']);
    Route::delete('/households/shopping/lists/{itemId}', [PlanController::class, 'destroyShoppingList']);
    Route::post('/households/shopping/lists/{itemId}/recipe/{recipeId}/delete', [PlanController::class, 'removeRecipe']);
    Route::post('/households/shopping/lists/{itemId}/recipe/{recipeId}', [PlanController::class, 'addOneRecipe']);
    Route::post('/households/shopping/lists/{itemId}/recipe', [PlanController::class, 'addRecipe']);
    Route::put('/households/shopping/lists/{itemId}/label-settings', [OpsController::class, 'labelSettings']);
    Route::get('/households/shopping/lists/{itemId}', [PlanController::class, 'shoppingList']);

    Route::get('/admin/about', [AdminController::class, 'about']);
    Route::get('/admin/about/statistics', [AdminController::class, 'statistics']);
    Route::get('/admin/about/check', [AdminController::class, 'check']);
    Route::get('/admin/users', [AdminController::class, 'users']);
    Route::post('/admin/users', [AdminController::class, 'storeUser']);
    Route::post('/admin/users/unlock', [AdminController::class, 'unlock']);
    Route::post('/admin/users/password-reset-token', [AdminController::class, 'passwordResetToken']);
    Route::get('/admin/users/{id}', [AdminController::class, 'user']);
    Route::put('/admin/users/{id}', [AdminController::class, 'updateUser']);
    Route::delete('/admin/users/{id}', [AdminController::class, 'destroyUser']);
    Route::get('/admin/groups', [AdminController::class, 'groups']);
    Route::post('/admin/groups', [OpsController::class, 'storeGroup']);
    Route::delete('/admin/groups/{id}', [OpsController::class, 'destroyGroup']);
    Route::get('/admin/households', [AdminController::class, 'households']);
    Route::get('/admin/backups', [OpsController::class, 'backups']);
    Route::post('/admin/backups', [OpsController::class, 'createBackup']);
    Route::post('/admin/backups/upload', [OpsController::class, 'uploadBackup']);
    Route::get('/admin/backups/{fileName}', [OpsController::class, 'downloadBackup']);
    Route::delete('/admin/backups/{fileName}', [OpsController::class, 'destroyBackup']);
    Route::post('/admin/backups/{fileName}/restore', [OpsController::class, 'restoreBackup']);
    Route::get('/backups/available', [OpsController::class, 'backups']);
    Route::post('/backups/export/database', [OpsController::class, 'createBackup']);
    Route::post('/backups/upload', [OpsController::class, 'uploadBackup']);
    Route::get('/backups/{fileName}/download', [OpsController::class, 'downloadBackup']);
    Route::delete('/backups/{fileName}/delete', [OpsController::class, 'destroyBackup']);
    Route::post('/backups/{fileName}/import', [OpsController::class, 'restoreBackup']);
    Route::get('/admin/maintenance', [OpsController::class, 'maintenance']);
    Route::get('/admin/maintenance/storage', [OpsController::class, 'storageDetails']);
    Route::get('/admin/maintenance/logs', [OpsController::class, 'logs']);
    Route::post('/admin/maintenance/clean/temp', [OpsController::class, 'clean']);
    Route::post('/admin/maintenance/clean/images', [OpsController::class, 'clean']);
    Route::post('/admin/maintenance/clean/recipe-folders', [OpsController::class, 'clean']);
    Route::post('/admin/maintenance/clean/logs', [OpsController::class, 'clean']);
    Route::get('/admin/analytics', [OpsController::class, 'analytics']);
    Route::post('/admin/email', [OpsController::class, 'email']);
    Route::get('/households/shopping/items', [PlanController::class, 'items']);
    Route::post('/households/shopping/items/create-bulk', [PlanController::class, 'storeItem']);
    Route::post('/households/shopping/items', [PlanController::class, 'storeItem']);
    Route::put('/households/shopping/items/{itemId}', [PlanController::class, 'updateItem']);
    Route::put('/households/shopping/items', [PlanController::class, 'updateItems']);
    Route::delete('/households/shopping/items/{itemId}', [PlanController::class, 'destroyItem']);
    Route::delete('/households/shopping/items', [PlanController::class, 'destroyItems']);
    Route::get('/households/webhooks', [HouseholdController::class, 'webhooks']);
    Route::post('/households/webhooks', [HouseholdController::class, 'storeWebhook']);
    Route::get('/households/webhooks/{id}', [HouseholdController::class, 'webhook']);
    Route::put('/households/webhooks/{id}', [HouseholdController::class, 'updateWebhook']);
    Route::post('/households/webhooks/{id}/test', [HouseholdController::class, 'testWebhook']);
    Route::delete('/households/webhooks/{id}', [HouseholdController::class, 'destroyWebhook']);
    Route::get('/groups/reports', [OpsController::class, 'reports']);
    Route::get('/groups/reports/{id}', [OpsController::class, 'report']);
    Route::delete('/groups/reports/{id}', [OpsController::class, 'destroyReport']);
    Route::post('/groups/seeders/foods', [OpsController::class, 'seedFoods']);
    Route::post('/groups/seeders/units', [OpsController::class, 'seedUnits']);
    Route::post('/groups/migrations', [OpsController::class, 'migration']);
    Route::get('/groups/storage', [OpsController::class, 'storage']);
    Route::get('/groups/households', [OpsController::class, 'households']);
    Route::post('/groups/households', [OpsController::class, 'storeHousehold']);
    Route::put('/groups/households/{id}', [OpsController::class, 'updateHousehold']);
    Route::delete('/groups/households/{id}', [OpsController::class, 'destroyHousehold']);
    Route::get('/households/events/notifications', [OpsController::class, 'notifiers']);
    Route::post('/households/events/notifications', [OpsController::class, 'storeNotifier']);
    Route::put('/households/events/notifications/{id}', [OpsController::class, 'updateNotifier']);
    Route::post('/households/events/notifications/{id}/test', [OpsController::class, 'testNotifier']);
    Route::delete('/households/events/notifications/{id}', [OpsController::class, 'destroyNotifier']);
    Route::get('/households/recipe-actions', [OpsController::class, 'actions']);
    Route::post('/households/recipe-actions', [OpsController::class, 'storeAction']);
    Route::put('/households/recipe-actions/{id}', [OpsController::class, 'updateAction']);
    Route::post('/households/recipe-actions/{id}/trigger/{slug}', [OpsController::class, 'triggerAction']);
    Route::delete('/households/recipe-actions/{id}', [OpsController::class, 'destroyAction']);
    Route::post('/households/invitations/email', [OpsController::class, 'email']);
    Route::get('/households/invitations', [HouseholdController::class, 'invitations']);
    Route::post('/households/invitations', [HouseholdController::class, 'storeInvitation']);

    Route::post('/parser/ingredient', [ParserController::class, 'ingredient']);
    Route::post('/parser/ingredients', [ParserController::class, 'ingredients']);
});
