apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: training
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
