// This Code is auto generated by gen_ts_unit_systems.py
// Conversion factors come from Pint via dev/code-generation/unit_systems.py. Do not edit them
// here, and do not add new ones: edit SELECTION in that module and re-run `task dev:generate`.

export type UnitDimension = "mass" | "volume";

export type UnitSystem = "metric" | "us" | "imperial";

/** A unit an ingredient may be stored in, and how to reduce it to a base magnitude. */
export interface StandardizedUnit {
  dimension: UnitDimension;
  /** How many base units (grams for mass, millilitres for volume) are in one of this unit. */
  base: number;
}

/** A display unit, and the point at which it takes over from the rung below it. */
export interface UnitRung {
  /** The Pint unit name. Doubles as the i18n key for the unit's display names. */
  unit: string;
  base: number;
  /** Whole units needed before this rung takes over. */
  takeover: number;
  /** Whether to render the quantity as a fraction rather than a decimal. */
  fraction: boolean;
}

export const STANDARDIZED_UNITS: Record<string, StandardizedUnit> = {
  fluid_ounce: { dimension: "volume", base: 29.5735295625 },
  cup: { dimension: "volume", base: 236.5882365 },
  ounce: { dimension: "mass", base: 28.349523125 },
  pound: { dimension: "mass", base: 453.59237 },
  milliliter: { dimension: "volume", base: 1.0 },
  liter: { dimension: "volume", base: 1000.0 },
  gram: { dimension: "mass", base: 1.0 },
  kilogram: { dimension: "mass", base: 1000.0 },
};

export const UNIT_SYSTEMS: Record<UnitSystem, Record<UnitDimension, UnitRung[]>> = {
  metric: {
    mass: [
      { unit: "gram", base: 1.0, takeover: 1.0, fraction: false },
      { unit: "kilogram", base: 1000.0, takeover: 1.0, fraction: false },
    ],
    volume: [
      { unit: "milliliter", base: 1.0, takeover: 1.0, fraction: false },
      { unit: "liter", base: 1000.0, takeover: 1.0, fraction: false },
    ],
  },
  us: {
    mass: [
      { unit: "ounce", base: 28.349523125, takeover: 1.0, fraction: true },
      { unit: "pound", base: 453.59237, takeover: 1.0, fraction: true },
    ],
    volume: [
      { unit: "teaspoon", base: 4.92892159375, takeover: 1.0, fraction: true },
      { unit: "tablespoon", base: 14.78676478125, takeover: 1.0, fraction: true },
      { unit: "cup", base: 236.5882365, takeover: 0.25, fraction: true },
      { unit: "quart", base: 946.352946, takeover: 1.0, fraction: true },
      { unit: "gallon", base: 3785.411784, takeover: 1.0, fraction: true },
    ],
  },
  imperial: {
    mass: [
      { unit: "ounce", base: 28.349523125, takeover: 1.0, fraction: true },
      { unit: "pound", base: 453.59237, takeover: 1.0, fraction: true },
    ],
    volume: [
      { unit: "milliliter", base: 1.0, takeover: 1.0, fraction: false },
      { unit: "imperial_pint", base: 568.26125, takeover: 1.0, fraction: true },
      { unit: "imperial_quart", base: 1136.5225, takeover: 1.0, fraction: true },
      { unit: "imperial_gallon", base: 4546.09, takeover: 1.0, fraction: true },
    ],
  },
};
