---
name: Bug Report
description: "Submit a bug for the latest version of Mealie"
title: "[BUG] - YOUR DESCRIPTIVE TITLE GOES HERE"
labels: ["bug", "triage"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: |
        Please confirm and check all the following prior to submission. If you do not do this, your
        issue may be closed.
      options:
        - label: This is not a feature request.
          required: true
        - label: I added a very descriptive title to this issue (title field is above this).
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it.
          required: true
        - label: I searched the Mealie documentation, with the integrated search.
          required: true
        - label: I already read the docs and didn't find an answer.
          required: true
        - label: This issue can be replicated on the demo site (https://demo.mealie.io/).
          required: false
  - type: textarea
    id: description
    attributes:
      label: What is the issue you are experiencing?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Please provide relevant logs
      placeholder: For example from `docker compose logs` or other system logs.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Mealie Version
      placeholder: Docker image, as well as 'Build' tag from https://yourmealieurl/admin/site-settings, if UI is working
  - type: dropdown
    id: os
    attributes:
      label: Deployment
      description: What Deployment system are you using?
      multiple: true
      options:
        - Docker (Linux)
        - Docker (Windows)
        - Docker (Synology)
        - Unraid
        - TrueNAS
        - Other (please specify below)
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Additional Deployment Details
