contact_links:
  - name: Feature Requests
    url: https://github.com/mealie-recipes/mealie/discussions/new?category=feature-request
    about: Please add any Feature Requests as a Github Discussion using the form in this issue.
