"""add color to tags and categories

Revision ID: c2e7e37d45cb
Revises: 2ea7a807915c
Create Date: 2023-01-03 18:16:38.472599

"""
import sqlalchemy as sa

import mealie.db.migration_types
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2e7e37d45cb"
down_revision = "2ea7a807915c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("color", sa.String(), nullable=False))
    op.create_index(op.f("ix_categories_color"), "categories", ["color"], unique=False)
    op.add_column("tags", sa.Column("color", sa.String(), nullable=False))
    op.create_index(op.f("ix_tags_color"), "tags", ["color"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_color"), table_name="tags")
    op.drop_column("tags", "color")
    op.drop_index(op.f("ix_categories_color"), table_name="categories")
    op.drop_column("categories", "color")
    # ### end Alembic commands ###
