"""added household recipe lock setting and household management user permission

Revision ID: be568e39ffdf
Revises: feecc8ffb956
Create Date: 2024-09-02 21:39:49.210355

"""

from textwrap import dedent

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "be568e39ffdf"
down_revision = "feecc8ffb956"
branch_labels = None
depends_on = None


def populate_defaults():
    op.execute(
        dedent(
            """
            UPDATE household_preferences
            SET lock_recipe_edits_from_other_households = True
            WHERE lock_recipe_edits_from_other_households IS NULL
            """
        )
    )
    op.execute(
        dedent(
            """
            UPDATE users
            SET can_manage_household = False
            WHERE can_manage_household IS NULL
            """
        )
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "household_preferences",
        sa.Column("lock_recipe_edits_from_other_households", sa.Boolean(), nullable=True),
    )
    op.add_column("users", sa.Column("can_manage_household", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    populate_defaults()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "can_manage_household")
    op.alter_column(
        "recipes_ingredients", "quantity", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.drop_column("household_preferences", "lock_recipe_edits_from_other_households")
    # ### end Alembic commands ###
