"""add household to recipe last made, household to foods, and household to tools

Revision ID: b9e516e2d3b3
Revises: b1020f328e98
Create Date: 2024-11-20 17:30:41.152332

"""

import sqlalchemy as sa
from sqlalchemy import orm

import mealie.db.migration_types
from alembic import op
from mealie.core.root_logger import get_logger

# revision identifiers, used by Alembic.
revision = "b9e516e2d3b3"
down_revision: str | None = "b1020f328e98"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None

logger = get_logger()


def migrate_recipe_last_made_to_household(session: orm.Session):
    pass  # TODO


def migrate_foods_on_hand_to_household(session: orm.Session):
    pass  # TODO


def migrate_tools_on_hand_to_household(session: orm.Session):
    pass  # TODO


def migrate_to_new_models():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for migration_func in [
        migrate_recipe_last_made_to_household,
        migrate_foods_on_hand_to_household,
        migrate_tools_on_hand_to_household,
    ]:
        try:
            migration_func(session)
        except Exception:
            session.rollback()
            logger.exception(f"Error during new model migration ({migration_func.__name__})")
            raise

    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households_to_recipes",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("last_made", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id", "household_id", "recipe_id"),
        sa.UniqueConstraint("household_id", "recipe_id", name="household_id_recipe_id_key"),
    )
    with op.batch_alter_table("households_to_recipes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_households_to_recipes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_households_to_recipes_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_households_to_recipes_recipe_id"), ["recipe_id"], unique=False)

    op.create_table(
        "households_to_tools",
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("tool_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["tools.id"],
        ),
        sa.UniqueConstraint("household_id", "tool_id", name="household_id_tool_id_key"),
    )
    with op.batch_alter_table("households_to_tools", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_households_to_tools_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_households_to_tools_tool_id"), ["tool_id"], unique=False)

    op.create_table(
        "households_to_ingredient_foods",
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("food_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["ingredient_foods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.UniqueConstraint("household_id", "food_id", name="household_id_food_id_key"),
    )
    with op.batch_alter_table("households_to_ingredient_foods", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_households_to_ingredient_foods_food_id"), ["food_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_households_to_ingredient_foods_household_id"), ["household_id"], unique=False
        )

    # ### end Alembic commands ###

    migrate_to_new_models()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("households_to_ingredient_foods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_households_to_ingredient_foods_household_id"))
        batch_op.drop_index(batch_op.f("ix_households_to_ingredient_foods_food_id"))

    op.drop_table("households_to_ingredient_foods")
    with op.batch_alter_table("households_to_tools", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_households_to_tools_tool_id"))
        batch_op.drop_index(batch_op.f("ix_households_to_tools_household_id"))

    op.drop_table("households_to_tools")
    with op.batch_alter_table("households_to_recipes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_households_to_recipes_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_households_to_recipes_household_id"))
        batch_op.drop_index(batch_op.f("ix_households_to_recipes_created_at"))

    op.drop_table("households_to_recipes")
    # ### end Alembic commands ###
