def validate_locale(locale: str) -> bool:
    valid = {
        # CODE_GEN_ID: MESSAGE_LOCALES
        "af-ZA",
        "ar-SA",
        "bg-BG",
        "ca-ES",
        "cs-CZ",
        "da-DK",
        "de-DE",
        "el-GR",
        "en-GB",
        "en-US",
        "es-ES",
        "fi-FI",
        "fr-CA",
        "fr-FR",
        "fr-BE",
        "gl-ES",
        "he-IL",
        "hr-HR",
        "hu-HU",
        "is-IS",
        "it-IT",
        "ja-JP",
        "ko-KR",
        "lt-LT",
        "lv-LV",
        "nl-NL",
        "no-NO",
        "pl-PL",
        "pt-BR",
        "pt-PT",
        "ro-RO",
        "ru-RU",
        "sk-SK",
        "sl-SI",
        "sr-SP",
        "sv-SE",
        "tr-TR",
        "uk-UA",
        "vi-VN",
        "zh-CN",
        "zh-TW",
        # END: MESSAGE_LOCALES
    }

    return locale in valid
