from typing import Any

from jinja2 import Environment
from unit_systems import UnitDimension, UnitSystem, build_table
from utils import CodeDest, log

UNIT_SYSTEMS_TEMPLATE = """// This Code is auto generated by gen_ts_unit_systems.py
// Conversion factors come from Pint via dev/code-generation/unit_systems.py. Do not edit them
// here, and do not add new ones: edit SELECTION in that module and re-run `task dev:generate`.

export type UnitDimension = {{ dimension_union }};

export type UnitSystem = {{ system_union }};

/** A unit an ingredient may be stored in, and how to reduce it to a base magnitude. */
export interface StandardizedUnit {
  dimension: UnitDimension;
  /** How many base units (grams for mass, millilitres for volume) are in one of this unit. */
  base: number;
}

/** A display unit, and the point at which it takes over from the rung below it. */
export interface UnitRung {
  /** The Pint unit name. Doubles as the i18n key for the unit's display names. */
  unit: string;
  base: number;
  /** Whole units needed before this rung takes over. */
  takeover: number;
  /** Whether to render the quantity as a fraction rather than a decimal. */
  fraction: boolean;
}

export const STANDARDIZED_UNITS: Record<string, StandardizedUnit> = {
{%- for name, unit in units.items() %}
  {{ name }}: { dimension: "{{ unit.dimension }}", base: {{ unit.base | number }} },
{%- endfor %}
};

export const UNIT_SYSTEMS: Record<UnitSystem, Record<UnitDimension, UnitRung[]>> = {
{%- for system, dimensions in systems.items() %}
  {{ system }}: {
  {%- for dimension, rungs in dimensions.items() %}
    {{ dimension }}: [
    {%- for rung in rungs %}
      {{ rung | rung_literal }},
    {%- endfor %}
    ],
  {%- endfor %}
  },
{%- endfor %}
};
"""


def _number(value: float) -> str:
    """Render a float without the noise Pint's arithmetic leaves behind.

    Pint computes `pound` as 453.5923700000001 and `cup` as 236.58823649999994. Those trailing
    digits are artifacts of operation order rather than precision, and emitting them both makes
    the checked-in table hard to read and would churn its diff if a Pint release reassociated a
    product. 14 significant digits sits well inside a double's precision and recovers the exact
    defined values.
    """

    return repr(float(f"{value:.14g}"))


def _rung_literal(rung: dict[str, Any]) -> str:
    """Render one rung as a single-line object literal.

    Built here rather than in the template so the template itself stays under the line limit.
    """

    fields = [
        f'unit: "{rung["unit"]}"',
        f"base: {_number(rung['base'])}",
        f"takeover: {_number(rung['takeover'])}",
        f"fraction: {'true' if rung['fraction'] else 'false'}",
    ]

    return f"{{ {', '.join(fields)} }}"


def render_unit_systems_ts_file() -> str:
    table = build_table()

    # Filters have to be registered on the environment before the template is compiled, so this
    # can't use the bare `Template(...)` the other generators do.
    # keep_trailing_newline, or jinja eats the final newline and the file fails eslint's eol-last
    env = Environment(keep_trailing_newline=True)  # noqa: S701 - rendering TypeScript, not HTML
    env.filters["number"] = _number
    env.filters["rung_literal"] = _rung_literal
    tmpl = env.from_string(UNIT_SYSTEMS_TEMPLATE)

    return tmpl.render(
        dimension_union=" | ".join(f'"{dimension.value}"' for dimension in UnitDimension),
        system_union=" | ".join(f'"{system.value}"' for system in UnitSystem),
        units=table["units"],
        systems=table["systems"],
    )


def main():
    log.debug(f"generating unit systems ts file -> {CodeDest.unit_systems}")
    with open(CodeDest.unit_systems, "w") as f:
        f.write(render_unit_systems_ts_file())


if __name__ == "__main__":
    main()
