# This file is auto-generated by gen_schema_exports.py
from .multi_purpose_label import (
    MultiPurposeLabelCreate,
    MultiPurposeLabelOut,
    MultiPurposeLabelPagination,
    MultiPurposeLabelSave,
    MultiPurposeLabelSummary,
    MultiPurposeLabelUpdate,
)

__all__ = [
    "MultiPurposeLabelCreate",
    "MultiPurposeLabelOut",
    "MultiPurposeLabelPagination",
    "MultiPurposeLabelSave",
    "MultiPurposeLabelSummary",
    "MultiPurposeLabelUpdate",
]
