// This Code is auto generated by gen_global_components.py
export const LOCALES = [
  {
    name: "繁體中文 (Chinese traditional)",
    value: "zh-TW",
    progress: 68,
  },
  {
    name: "简体中文 (Chinese simplified)",
    value: "zh-CN",
    progress: 56,
  },
  {
    name: "Tiếng Việt (Vietnamese)",
    value: "vi-VN",
    progress: 0,
  },
  {
    name: "Українська (Ukrainian)",
    value: "uk-UA",
    progress: 99,
  },
  {
    name: "Türkçe (Turkish)",
    value: "tr-TR",
    progress: 47,
  },
  {
    name: "Svenska (Swedish)",
    value: "sv-SE",
    progress: 91,
  },
  {
    name: "српски (Serbian)",
    value: "sr-SP",
    progress: 11,
  },
  {
    name: "Slovenian",
    value: "sl-SI",
    progress: 94,
  },
  {
    name: "Slovak",
    value: "sk-SK",
    progress: 85,
  },
  {
    name: "Pусский (Russian)",
    value: "ru-RU",
    progress: 57,
  },
  {
    name: "Română (Romanian)",
    value: "ro-RO",
    progress: 3,
  },
  {
    name: "Português (Portuguese)",
    value: "pt-PT",
    progress: 9,
  },
  {
    name: "Português do Brasil (Brazilian Portuguese)",
    value: "pt-BR",
    progress: 40,
  },
  {
    name: "Polski (Polish)",
    value: "pl-PL",
    progress: 89,
  },
  {
    name: "Norsk (Norwegian)",
    value: "no-NO",
    progress: 87,
  },
  {
    name: "Nederlands (Dutch)",
    value: "nl-NL",
    progress: 97,
  },
  {
    name: "Lithuanian",
    value: "lt-LT",
    progress: 64,
  },
  {
    name: "한국어 (Korean)",
    value: "ko-KR",
    progress: 0,
  },
  {
    name: "日本語 (Japanese)",
    value: "ja-JP",
    progress: 0,
  },
  {
    name: "Italiano (Italian)",
    value: "it-IT",
    progress: 82,
  },
  {
    name: "Magyar (Hungarian)",
    value: "hu-HU",
    progress: 77,
  },
  {
    name: "עברית (Hebrew)",
    value: "he-IL",
    progress: 33,
  },
  {
    name: "Français (French)",
    value: "fr-FR",
    progress: 99,
  },
  {
    name: "French, Canada",
    value: "fr-CA",
    progress: 84,
  },
  {
    name: "Suomi (Finnish)",
    value: "fi-FI",
    progress: 22,
  },
  {
    name: "Español (Spanish)",
    value: "es-ES",
    progress: 94,
  },
  {
    name: "American English",
    value: "en-US",
    progress: 100.0,
  },
  {
    name: "British English",
    value: "en-GB",
    progress: 31,
  },
  {
    name: "Ελληνικά (Greek)",
    value: "el-GR",
    progress: 70,
  },
  {
    name: "Deutsch (German)",
    value: "de-DE",
    progress: 99,
  },
  {
    name: "Dansk (Danish)",
    value: "da-DK",
    progress: 99,
  },
  {
    name: "Čeština (Czech)",
    value: "cs-CZ",
    progress: 89,
  },
  {
    name: "Català (Catalan)",
    value: "ca-ES",
    progress: 95,
  },
  {
    name: "Bulgarian",
    value: "bg-BG",
    progress: 0,
  },
  {
    name: "العربية (Arabic)",
    value: "ar-SA",
    progress: 24,
  },
  {
    name: "Afrikaans (Afrikaans)",
    value: "af-ZA",
    progress: 9,
  },
]
