// This Code is auto generated by gen_global_components.py
export const LOCALES = [
  {
    name: "繁體中文 (Chinese traditional)",
    value: "zh-TW",
    progress: 28,
  },
  {
    name: "简体中文 (Chinese simplified)",
    value: "zh-CN",
    progress: 65,
  },
  {
    name: "Tiếng Việt (Vietnamese)",
    value: "vi-VN",
    progress: 2,
  },
  {
    name: "Українська (Ukrainian)",
    value: "uk-UA",
    progress: 99,
  },
  {
    name: "Türkçe (Turkish)",
    value: "tr-TR",
    progress: 50,
  },
  {
    name: "Svenska (Swedish)",
    value: "sv-SE",
    progress: 71,
  },
  {
    name: "српски (Serbian)",
    value: "sr-SP",
    progress: 4,
  },
  {
    name: "Slovenian",
    value: "sl-SI",
    progress: 49,
  },
  {
    name: "Slovak",
    value: "sk-SK",
    progress: 97,
  },
  {
    name: "Pусский (Russian)",
    value: "ru-RU",
    progress: 99,
  },
  {
    name: "Română (Romanian)",
    value: "ro-RO",
    progress: 32,
  },
  {
    name: "Português (Portuguese)",
    value: "pt-PT",
    progress: 99,
  },
  {
    name: "Português do Brasil (Brazilian Portuguese)",
    value: "pt-BR",
    progress: 98,
  },
  {
    name: "Polski (Polish)",
    value: "pl-PL",
    progress: 97,
  },
  {
    name: "Norsk (Norwegian)",
    value: "no-NO",
    progress: 85,
  },
  {
    name: "Nederlands (Dutch)",
    value: "nl-NL",
    progress: 98,
  },
  {
    name: "Latvian",
    value: "lv-LV",
    progress: 1,
  },
  {
    name: "Lithuanian",
    value: "lt-LT",
    progress: 97,
  },
  {
    name: "한국어 (Korean)",
    value: "ko-KR",
    progress: 5,
  },
  {
    name: "日本語 (Japanese)",
    value: "ja-JP",
    progress: 11,
  },
  {
    name: "Italiano (Italian)",
    value: "it-IT",
    progress: 96,
  },
  {
    name: "Magyar (Hungarian)",
    value: "hu-HU",
    progress: 99,
  },
  {
    name: "Croatian",
    value: "hr-HR",
    progress: 97,
  },
  {
    name: "עברית (Hebrew)",
    value: "he-IL",
    progress: 99,
  },
  {
    name: "Galician",
    value: "gl-ES",
    progress: 1,
  },
  {
    name: "Français (French)",
    value: "fr-FR",
    progress: 99,
  },
  {
    name: "French, Canada",
    value: "fr-CA",
    progress: 97,
  },
  {
    name: "Suomi (Finnish)",
    value: "fi-FI",
    progress: 95,
  },
  {
    name: "Español (Spanish)",
    value: "es-ES",
    progress: 76,
  },
  {
    name: "American English",
    value: "en-US",
    progress: 100.0,
  },
  {
    name: "British English",
    value: "en-GB",
    progress: 4,
  },
  {
    name: "Ελληνικά (Greek)",
    value: "el-GR",
    progress: 35,
  },
  {
    name: "Deutsch (German)",
    value: "de-DE",
    progress: 99,
  },
  {
    name: "Dansk (Danish)",
    value: "da-DK",
    progress: 100,
  },
  {
    name: "Čeština (Czech)",
    value: "cs-CZ",
    progress: 66,
  },
  {
    name: "Català (Catalan)",
    value: "ca-ES",
    progress: 61,
  },
  {
    name: "Bulgarian",
    value: "bg-BG",
    progress: 99,
  },
  {
    name: "العربية (Arabic)",
    value: "ar-SA",
    progress: 16,
  },
  {
    name: "Afrikaans (Afrikaans)",
    value: "af-ZA",
    progress: 96,
  },
]
