BASE = "/api"

ALL_RECIPES = BASE + "/recipes"

RECIPES_PREFIX = BASE + "/recipes"
RECIPES_ALL = RECIPES_PREFIX
RECIPES_CREATE = RECIPES_PREFIX + "/create"
RECIPES_CREATE_URL = RECIPES_PREFIX + "/create-url"

CATEGORIES_PREFIX = BASE + "/categories"
TAGS_PREFIX = BASE + "/tags"

MEALPLAN_PREFIX = BASE + "/meal-plans"
MEALPLAN_ALL = MEALPLAN_PREFIX + "/all"
MEALPLAN_CREATE = MEALPLAN_PREFIX + "/create"
MEALPLAN_THIS_WEEK = MEALPLAN_PREFIX + "/this-week"
MEALPLAN_TODAY = MEALPLAN_PREFIX + "/today"

SETTINGS_PREFIX = BASE + "/site-settings"
SETTINGS_UPDATE = SETTINGS_PREFIX
TEST_WEBHOOKS = SETTINGS_PREFIX + "/webhooks/test"

THEMES_PREFIX = BASE + "/themes"
THEMES_CREATE = THEMES_PREFIX + "/create"

BACKUPS_PREFIX = BASE + "/backups"
BACKUPS_AVAILABLE = BACKUPS_PREFIX + "/available"
BACKUPS_EXPORT = BACKUPS_PREFIX + "/export/database"
BACKUPS_UPLOAD = BACKUPS_PREFIX + "/upload"

MIGRATIONS_PREFIX = BASE + "/migrations"
