apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-env
  namespace: platform
data:
  MINIO_ENDPOINT: "http://minio-service.platform.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service.platform.svc.cluster.local:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.platform.svc.cluster.local:9000"
  POSTGRES_HOST: "postgres.platform.svc.cluster.local"
  POSTGRES_DB: "mealie"
  MINIO_BUCKET: "mlflow-artifacts"
  DATA_BUCKET: "training-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-env
  namespace: mealie
data:
  MINIO_ENDPOINT: "http://minio-service.platform.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service.platform.svc.cluster.local:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.platform.svc.cluster.local:9000"
  POSTGRES_HOST: "postgres.platform.svc.cluster.local"
  POSTGRES_DB: "mealie"
  MINIO_BUCKET: "mlflow-artifacts"
  DATA_BUCKET: "training-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-env
  namespace: serving
data:
  MINIO_ENDPOINT: "http://minio-service.platform.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service.platform.svc.cluster.local:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.platform.svc.cluster.local:9000"
  POSTGRES_HOST: "postgres.platform.svc.cluster.local"
  POSTGRES_DB: "mealie"
  MINIO_BUCKET: "mlflow-artifacts"
  DATA_BUCKET: "training-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-env
  namespace: data
data:
  MINIO_ENDPOINT: "http://minio-service.platform.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service.platform.svc.cluster.local:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.platform.svc.cluster.local:9000"
  POSTGRES_HOST: "postgres.platform.svc.cluster.local"
  POSTGRES_DB: "mealie"
  MINIO_BUCKET: "mlflow-artifacts"
  DATA_BUCKET: "training-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-env
  namespace: training
data:
  MINIO_ENDPOINT: "http://minio-service.platform.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service.platform.svc.cluster.local:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.platform.svc.cluster.local:9000"
  POSTGRES_HOST: "postgres.platform.svc.cluster.local"
  POSTGRES_DB: "mealie"
  MINIO_BUCKET: "mlflow-artifacts"
  DATA_BUCKET: "training-data"
