name: Fork Build

on:
  push:
    branches: [mealie-next]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Get yarn cache dir
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        working-directory: frontend
      - run: yarn generate
        working-directory: frontend
      - uses: actions/upload-artifact@v6
        with:
          name: frontend-dist
          path: frontend/dist
          retention-days: 1

  build-package:
    name: Build Python package
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install uv
      - uses: actions/download-artifact@v6
        with:
          name: frontend-dist
          path: mealie/frontend
      - name: Override version
        run: echo '__version__ = "dev"' > ./mealie/__init__.py
      - name: Build package
        env:
          SKIP_PACKAGE_DEPS: true
        run: task py:package
      - uses: actions/upload-artifact@v6
        with:
          name: backend-dist
          path: dist
          retention-days: 1

  publish:
    name: Build and push Docker image
    needs: build-package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v6
        with:
          name: backend-dist
          path: dist
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          build-contexts: packages=dist
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mealie:dev
          build-args: COMMIT=${{ github.sha }}
