name: Frontend - Nightly Build

on:
  push:
    branches:
      - mealie-next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout
      #
      - name: checkout code
        uses: actions/checkout@v2
      #
      # Setup QEMU
      #
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      #
      # Setup Buildx
      #
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      #
      # Login to Docker Hub
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # Build
      #
      - name: build the image
        working-directory: "frontend"
        run: |
          docker build --push --no-cache \
            --tag hkotel/mealie:frontend-nightly \
            --platform linux/amd64,linux/arm64 .
      #
      # Build Discord Notification
      #
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_NIGHTLY_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "🚀  A New build of mealie:frontend-nightly is available"
