name: Backend Lint and Test

on:
  workflow_call:

jobs:
  setup-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [sqlite, postgres]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python Backend
        uses: ./.github/actions/setup-python-backend
        with:
          install-postgres: ${{ matrix.database == 'postgres' }}

      - name: Cache Python Environment
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: python-deps-${{ matrix.database }}-${{ hashFiles('poetry.lock', 'pyproject.toml') }}

  lint-and-typecheck:
    runs-on: ubuntu-latest
    needs: setup-python

    env:
      PRODUCTION: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore Python Environment (SQLite)
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: python-deps-sqlite-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
          fail-on-cache-miss: true

      - name: Setup Task (only)
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ github.token }}

      - name: Formatting (Ruff)
        run: |
          poetry run ruff format . --check

      - name: Lint (Ruff)
        run: |
          task py:lint

      - name: Mypy Typecheck
        run: |
          task py:mypy

      - name: GitHub Actions Test Suite Sync
        run: |
          task py:test:validate-actions

  tests:
    runs-on: ubuntu-latest
    needs: setup-python

    env:
      PRODUCTION: false

    strategy:
      fail-fast: false
      matrix:
        # Database ENV Variables as Specified by Mealie
        Database: [sqlite, postgres]
        # Test directories to run in parallel
        TestSuite: [
          # Long-running tests
          integration_tests/user_recipe_tests,
          # Everything else
          integration_tests/admin_tests,
          integration_tests/category_tag_tool_tests,
          integration_tests/core,
          integration_tests/public_explorer_tests,
          integration_tests/recipe_migration_tests,
          integration_tests/user_group_tests,
          integration_tests/user_household_tests,
          integration_tests/user_tests,
          multitenant_tests,
          unit_tests/core,
          unit_tests/pkgs,
          unit_tests/repository_tests,
          unit_tests/schema_tests,
          unit_tests/services_tests,
          unit_tests/validator_tests,
        ]

    # Services
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: mealie
          POSTGRES_PASSWORD: mealie
          POSTGRES_DB: mealie
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      ldap:
        image: rroemhild/test-openldap
        ports:
          - 10389:10389
          - 10636:10636

    # Steps
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore Python Environment
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: python-deps-${{ matrix.Database }}-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
          fail-on-cache-miss: true

      - name: Setup Task (only)
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ github.token }}

      - name: Pytest (${{ matrix.TestSuite }} - ${{ matrix.Database }})
        env:
          DB_ENGINE: ${{ matrix.Database }}
          POSTGRES_SERVER: localhost
          LDAP_AUTH_ENABLED: True
          LDAP_SERVER_URL: ldap://localhost:10389
          LDAP_TLS_INSECURE: true
          LDAP_ENABLE_STARTTLS: false
          LDAP_BASE_DN: "ou=people,dc=planetexpress,dc=com"
          LDAP_QUERY_BIND: "cn=admin,dc=planetexpress,dc=com"
          LDAP_QUERY_PASSWORD: "GoodNewsEveryone"
          LDAP_USER_FILTER: "(&(|({id_attribute}={input})({mail_attribute}={input}))(|(memberOf=cn=ship_crew,ou=people,dc=planetexpress,dc=com)(memberOf=cn=admin_staff,ou=people,dc=planetexpress,dc=com)))"
          LDAP_ADMIN_FILTER: "memberOf=cn=admin_staff,ou=people,dc=planetexpress,dc=com"
          LDAP_ID_ATTRIBUTE: uid
          LDAP_NAME_ATTRIBUTE: cn
          LDAP_MAIL_ATTRIBUTE: mail
        run: |
          poetry run pytest tests/${{ matrix.TestSuite }} -v
